import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const lora = localFont({
  src: "./fonts/Lora-VariableFont_wght.ttf",
  variable: "--font-lora",
  weight: "700 900",
});

const sourceSansRegular = localFont({
  src: "./fonts/SourceSans3-VariableFont_wght.ttf",
  variable: "--font-source-sans-pro",
  weight: "400 500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${sourceSansRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
